-- BitDrum Social Indexer Schema (PostgreSQL)

-- 1. Traders Table
-- Stores enriched on-chain metrics and rankings
CREATE TABLE IF NOT EXISTS traders (
    address TEXT PRIMARY KEY,
    display_name TEXT,
    tier TEXT DEFAULT 'SCOUT', -- ORACLE, PROPHET, TRADER, SCOUT
    markets_entered INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    draws INTEGER DEFAULT 0,
    net_pnl_sbtc NUMERIC DEFAULT 0,
    avg_stake_sbtc NUMERIC DEFAULT 0,
    consistency_score NUMERIC DEFAULT 0,
    composite_score NUMERIC DEFAULT 0,
    last_active TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Markets Table
-- Stores metadata for each market identified on-chain
CREATE TABLE IF NOT EXISTS markets (
    market_id TEXT PRIMARY KEY,
    opener_address TEXT REFERENCES traders(address),
    direction TEXT, -- UP, DOWN
    duration INTEGER, -- In seconds: 30, 60, 300
    strike_price NUMERIC,
    expiry_price NUMERIC,
    outcome TEXT, -- UP, DOWN, DRAW
    up_pool_sbtc NUMERIC DEFAULT 0,
    down_pool_sbtc NUMERIC DEFAULT 0,
    pom_profit_pct NUMERIC, -- The profit percentage determined by AI
    state TEXT DEFAULT 'OPEN', -- OPEN, LOCKED, SETTLED, CLAIMABLE, CLOSED
    opened_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    settled_at TIMESTAMP WITH TIME ZONE
);

-- 3. Stakes Table
-- Tracks individual participations in markets
CREATE TABLE IF NOT EXISTS stakes (
    stake_id SERIAL PRIMARY KEY,
    market_id TEXT REFERENCES markets(market_id),
    trader_address TEXT REFERENCES traders(address),
    direction TEXT,
    amount_sbtc NUMERIC,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. AI Signals Log
-- Records signals generated by the AI Agent for later accuracy tracking
CREATE TABLE IF NOT EXISTS ai_signals (
    signal_id SERIAL PRIMARY KEY,
    market_id TEXT REFERENCES markets(market_id),
    direction TEXT, -- BULLISH, BEARISH, NEUTRAL
    confidence INTEGER, -- 0-100
    rationale TEXT,
    is_accurate BOOLEAN, -- Populated after settlement
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Social Graph (Following)
CREATE TABLE IF NOT EXISTS follows (
    follower_address TEXT REFERENCES traders(address),
    following_address TEXT REFERENCES traders(address),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (follower_address, following_address)
);

-- 6. Subscriptions Table
CREATE TABLE IF NOT EXISTS subscriptions (
    address TEXT PRIMARY KEY REFERENCES traders(address),
    tier TEXT, -- PRO, ELITE
    paid_until TIMESTAMP WITH TIME ZONE,
    total_paid_lifetime NUMERIC DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_traders_composite_score ON traders(composite_score DESC);
CREATE INDEX IF NOT EXISTS idx_markets_state ON markets(state);
CREATE INDEX IF NOT EXISTS idx_stakes_market_id ON stakes(market_id);
CREATE INDEX IF NOT EXISTS idx_signals_market_id ON ai_signals(market_id);
